spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/playground
      username: sa
      password:
